export const GET_CURRENCIES = 'GET_CURRENCIES',
CURRENCIES_RECEIVED = 'CURRENCIES_RECEIVED',
LOAD_MORE = 'LOAD_MORE',
CURRENCIES_LOADED = 'CURRENCIES_LOADED',
CURRENCIES_UPDATED = 'CURRENCIES_UPDATED';
